language: java

jdk:
  - openjdk8

script: 
  - "mvn cobertura:cobertura"
  - java -jar evosuite-1.0.6.jar -class main.java.avl_java_travis.AVLTree -projectCP target/classes


after_success:
  - bash <(curl -s https://codecov.io/bash)
